### ISSUE TITLE
Add Unit Test

### ISSUE THREAD

**Issue by copperbeardy** [copperbeardy/GPSDistanceMeasure#4]
Create unit tests for the application

**Comment by Excolo** [comment]
I would like to work on this issue, but the application doesn't lend itself easily to unit testing, so I have a couple of questions.

Is there any particular parts you wanted to cover with testing? 
Do you have a preference for unit testing framework?
Would you mind a few refactorings to make the application more testable?

**Comment by copperbeardy** [comment]
refactoring if you would need to is ok. 

as for frameworks am most use to XUnit.

For what to unit test anything you think needs it, or as the application evolves should be unit tested. it does not just have to be a unit test, can be other forms as testing as well.

with it being a new application, I am mainly looking to ensure a good base to build upon.
