### ISSUE TITLE
Creata documentation

### ISSUE THREAD

**Issue by copperbeardy** [copperbeardy/GPSDistanceMeasure#8]
Create documentation to explain to new users how the app works. 

it should include images when making reference to parts of the UI

**Comment by hmumm** [comment]
I would like to help with this, how would you like the documentation added? Should a documentation folder be added?

**Comment by copperbeardy** [comment]
yes that would be helpful thank you

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
